// tools-data.js — the seed entity catalog for The Stack's data-backed pages
// (#16 entities table). Real, well-known AI-agent repos across categories. Star
// counts here are a seed floor; scripts/sync-tools.js refreshes them live from
// the GitHub API (the per-page unique data that keeps programmatic pages on the
// right side of Google's scaled-content policy — council §1.4).
//
// Each tool: { slug, name, owner, repo, url, category, lang, blurb, useCases[], alternatives[slug], stars }

export const CATEGORIES = {
  framework:    { name: "Agent frameworks", blurb: "Libraries for orchestrating LLM agents, tools, and multi-step control flow." },
  memory:       { name: "Agent memory", blurb: "Long-term and working memory for agents that persist across runs." },
  vectordb:     { name: "Vector databases", blurb: "Embedding stores powering retrieval for RAG and agent recall." },
  mcp:          { name: "MCP & tool servers", blurb: "Model Context Protocol servers and tool-calling infrastructure." },
  eval:         { name: "Evals & testing", blurb: "Measuring agent and LLM output quality, regressions, and safety." },
  observability:{ name: "Observability", blurb: "Tracing, logging, and monitoring for LLM and agent systems." },
  runtime:      { name: "Agent runtimes", blurb: "Sandboxes and execution environments for running agent code/tools." },
};

export const TOOLS = [
  { slug: "langgraph", name: "LangGraph", owner: "langchain-ai", repo: "langgraph", category: "framework", lang: "Python", stars: 12000,
    blurb: "Graph-based orchestration for stateful, multi-actor agent workflows with explicit control flow and checkpointing.",
    useCases: ["stateful multi-agent workflows", "human-in-the-loop", "long-running agents"], alternatives: ["crewai", "autogen", "llama-index"] },
  { slug: "crewai", name: "CrewAI", owner: "crewAIInc", repo: "crewAI", category: "framework", lang: "Python", stars: 24000,
    blurb: "Role-playing autonomous agents that collaborate as a 'crew' with defined roles, goals, and task delegation.",
    useCases: ["role-based multi-agent teams", "task delegation", "rapid prototyping"], alternatives: ["langgraph", "autogen"] },
  { slug: "autogen", name: "AutoGen", owner: "microsoft", repo: "autogen", category: "framework", lang: "Python", stars: 35000,
    blurb: "Microsoft's framework for multi-agent conversation, with a programming model for agents that talk to each other and tools.",
    useCases: ["conversational multi-agent", "code execution", "research"], alternatives: ["langgraph", "crewai", "semantic-kernel"] },
  { slug: "llama-index", name: "LlamaIndex", owner: "run-llama", repo: "llama_index", category: "framework", lang: "Python", stars: 37000,
    blurb: "Data framework for connecting LLMs to private data — indexing, retrieval, and agentic RAG over your documents.",
    useCases: ["RAG", "document agents", "knowledge assistants"], alternatives: ["langgraph", "haystack"] },
  { slug: "dspy", name: "DSPy", owner: "stanfordnlp", repo: "dspy", category: "framework", lang: "Python", stars: 19000,
    blurb: "Programming — not prompting — language models: compile declarative pipelines into optimized prompts/weights.",
    useCases: ["prompt optimization", "compound AI systems", "self-improving pipelines"], alternatives: ["langgraph", "llama-index"] },
  { slug: "pydantic-ai", name: "Pydantic AI", owner: "pydantic", repo: "pydantic-ai", category: "framework", lang: "Python", stars: 7000,
    blurb: "Type-safe agent framework from the Pydantic team — structured outputs, dependency injection, and model-agnostic agents.",
    useCases: ["type-safe agents", "structured outputs", "production Python"], alternatives: ["langgraph", "crewai"] },
  { slug: "openai-agents-sdk", name: "OpenAI Agents SDK", owner: "openai", repo: "openai-agents-python", category: "framework", lang: "Python", stars: 14000,
    blurb: "OpenAI's lightweight agent framework — a small set of primitives (Agents, Handoffs, Guardrails, Sessions); provider-agnostic via LiteLLM. Evolved from Swarm.",
    useCases: ["minimal orchestration", "agent handoffs", "guardrailed agents"], alternatives: ["pydantic-ai", "agno", "langgraph"] },
  { slug: "agno", name: "Agno", owner: "agno-agi", repo: "agno", category: "framework", lang: "Python", stars: 31000,
    blurb: "Batteries-included agent runtime — built-in memory, knowledge/RAG, and AgentOS, a control plane you run in your own cloud. Formerly Phidata.",
    useCases: ["full-stack agents", "built-in memory + RAG", "self-hosted control plane"], alternatives: ["langgraph", "crewai", "pydantic-ai"] },
  { slug: "google-adk", name: "Google ADK", owner: "google", repo: "adk-python", category: "framework", lang: "Python", stars: 12000,
    blurb: "Google's Agent Development Kit — a code-first, model-agnostic toolkit for building, evaluating, and deploying multi-agent systems. Optimized for Gemini.",
    useCases: ["multi-agent systems", "agent evaluation", "Gemini-first agents"], alternatives: ["langgraph", "crewai", "openai-agents-sdk"] },
  { slug: "claude-agent-sdk", name: "Claude Agent SDK", owner: "anthropics", repo: "claude-agent-sdk-python", category: "framework", lang: "Python", stars: 5000,
    blurb: "Anthropic's SDK for building agents on Claude — the harness behind Claude Code, with in-process tools, hooks, and an interactive client. Formerly the Claude Code SDK.",
    useCases: ["Claude-native agents", "coding agents", "custom tools + hooks"], alternatives: ["langgraph", "openai-agents-sdk", "pydantic-ai"] },
  { slug: "mem0", name: "Mem0", owner: "mem0ai", repo: "mem0", category: "memory", lang: "Python", stars: 25000,
    blurb: "A memory layer for AI agents — extracts, stores, and retrieves user/agent facts across sessions.",
    useCases: ["personalized agents", "cross-session memory", "user preference recall"], alternatives: ["letta", "zep"] },
  { slug: "letta", name: "Letta (MemGPT)", owner: "letta-ai", repo: "letta", category: "memory", lang: "Python", stars: 16000,
    blurb: "Stateful agents with long-term memory and self-editing context, evolved from the MemGPT research.",
    useCases: ["persistent agents", "self-editing memory", "long conversations"], alternatives: ["mem0", "zep"] },
  { slug: "zep", name: "Zep", owner: "getzep", repo: "zep", category: "memory", lang: "Go", stars: 3000,
    blurb: "Long-term memory store for agents with a temporal knowledge graph of facts and their validity over time.",
    useCases: ["temporal memory", "knowledge graphs", "fact recall"], alternatives: ["mem0", "letta"] },
  { slug: "chroma", name: "Chroma", owner: "chroma-core", repo: "chroma", category: "vectordb", lang: "Rust", stars: 19000,
    blurb: "Open-source embedding database designed for simplicity — the default vector store for many RAG prototypes.",
    useCases: ["RAG", "semantic search", "local prototyping"], alternatives: ["qdrant", "weaviate", "milvus"] },
  { slug: "qdrant", name: "Qdrant", owner: "qdrant", repo: "qdrant", category: "vectordb", lang: "Rust", stars: 23000,
    blurb: "High-performance vector search engine with rich filtering, written in Rust for production-scale retrieval.",
    useCases: ["production RAG", "filtered search", "high throughput"], alternatives: ["chroma", "weaviate", "milvus"] },
  { slug: "weaviate", name: "Weaviate", owner: "weaviate", repo: "weaviate", category: "vectordb", lang: "Go", stars: 13000,
    blurb: "Open-source vector database with hybrid search and built-in modules for vectorization and RAG.",
    useCases: ["hybrid search", "RAG", "multimodal"], alternatives: ["qdrant", "chroma", "milvus"] },
  { slug: "milvus", name: "Milvus", owner: "milvus-io", repo: "milvus", category: "vectordb", lang: "Go", stars: 32000,
    blurb: "Cloud-native vector database built for billion-scale similarity search.",
    useCases: ["billion-scale search", "enterprise RAG", "distributed"], alternatives: ["qdrant", "weaviate"] },
  { slug: "pgvector", name: "pgvector", owner: "pgvector", repo: "pgvector", category: "vectordb", lang: "C", stars: 14000,
    blurb: "Vector similarity search inside Postgres — keep embeddings next to your relational data.",
    useCases: ["RAG on existing Postgres", "no new infra", "transactional + vector"], alternatives: ["qdrant", "chroma"] },
  { slug: "lancedb", name: "LanceDB", owner: "lancedb", repo: "lancedb", category: "vectordb", lang: "Rust", stars: 10700,
    blurb: "Embedded, in-process vector database on the columnar Lance format — versioned, updatable, larger-than-RAM retrieval with no server.",
    useCases: ["embedded vector search", "mutable/versioned datasets", "multimodal RAG"], alternatives: ["sqlite-vec", "chroma", "duckdb"] },
  { slug: "sqlite-vec", name: "sqlite-vec", owner: "asg017", repo: "sqlite-vec", category: "vectordb", lang: "C", stars: 7800,
    blurb: "A single-file SQLite extension for vector search — exact brute-force KNN that lives inside the database you already ship.",
    useCases: ["vectors inside SQLite", "edge/local agents", "exact small-scale search"], alternatives: ["lancedb", "pgvector", "chroma"] },
  { slug: "duckdb", name: "DuckDB", owner: "duckdb", repo: "duckdb", category: "vectordb", lang: "C++", stars: 39000,
    blurb: "In-process analytical database whose vss extension adds an HNSW vector index — vector search alongside your columnar analytics.",
    useCases: ["analytical + vector search", "embedded OLAP", "batch retrieval"], alternatives: ["lancedb", "sqlite-vec", "pgvector"] },
  { slug: "mcp-servers", name: "MCP Servers", owner: "modelcontextprotocol", repo: "servers", category: "mcp", lang: "TypeScript", stars: 50000,
    blurb: "The reference collection of Model Context Protocol servers — connect agents to files, GitHub, databases, and more.",
    useCases: ["tool integration", "agent connectors", "MCP ecosystem"], alternatives: ["fastmcp"] },
  { slug: "fastmcp", name: "FastMCP", owner: "jlowin", repo: "fastmcp", category: "mcp", lang: "Python", stars: 12000,
    blurb: "The fast, Pythonic way to build MCP servers and clients — decorators over boilerplate.",
    useCases: ["building MCP servers", "Python tooling", "rapid integration"], alternatives: ["mcp-servers"] },
  { slug: "langfuse", name: "Langfuse", owner: "langfuse", repo: "langfuse", category: "observability", lang: "TypeScript", stars: 11000,
    blurb: "Open-source LLM engineering platform — tracing, evals, prompt management, and metrics for agent apps.",
    useCases: ["LLM tracing", "prompt management", "production monitoring"], alternatives: ["phoenix", "helicone"] },
  { slug: "phoenix", name: "Phoenix", owner: "Arize-ai", repo: "phoenix", category: "observability", lang: "Jupyter Notebook", stars: 6000,
    blurb: "Arize's open-source observability for LLM apps — OpenTelemetry-based tracing and evaluation.",
    useCases: ["OTel tracing", "evaluation", "debugging RAG"], alternatives: ["langfuse", "helicone"] },
  { slug: "helicone", name: "Helicone", owner: "Helicone", repo: "helicone", category: "observability", lang: "TypeScript", stars: 4000,
    blurb: "Open-source observability for LLM apps via a proxy — logging, caching, and cost tracking with one header.",
    useCases: ["cost tracking", "request logging", "caching"], alternatives: ["langfuse", "phoenix"] },
  { slug: "ragas", name: "Ragas", owner: "explodinggradients", repo: "ragas", category: "eval", lang: "Python", stars: 9000,
    blurb: "Evaluation toolkit for RAG pipelines — faithfulness, answer relevancy, and context metrics without ground truth.",
    useCases: ["RAG evaluation", "faithfulness scoring", "CI for retrieval"], alternatives: ["deepeval", "promptfoo"] },
  { slug: "deepeval", name: "DeepEval", owner: "confident-ai", repo: "deepeval", category: "eval", lang: "Python", stars: 8000,
    blurb: "Pytest-like framework for unit-testing LLM outputs with metrics for hallucination, relevancy, and bias.",
    useCases: ["LLM unit tests", "regression testing", "CI gates"], alternatives: ["ragas", "promptfoo"] },
  { slug: "promptfoo", name: "promptfoo", owner: "promptfoo", repo: "promptfoo", category: "eval", lang: "TypeScript", stars: 7000,
    blurb: "Test-driven prompt and agent development — evals, red-teaming, and side-by-side model comparison from the CLI.",
    useCases: ["prompt evals", "red-teaming", "model comparison"], alternatives: ["deepeval", "ragas"] },
  { slug: "e2b", name: "E2B", owner: "e2b-dev", repo: "E2B", category: "runtime", lang: "TypeScript", stars: 8000,
    blurb: "Secure cloud sandboxes for running AI-generated code — the runtime layer for code-executing agents.",
    useCases: ["code execution", "agent sandboxes", "data analysis agents"], alternatives: ["modal"] },
  { slug: "temporal", name: "Temporal", owner: "temporalio", repo: "temporal", category: "runtime", lang: "Go", stars: 14000,
    blurb: "Durable execution platform — write long-running, failure-resilient agent workflows as ordinary code.",
    useCases: ["durable agent workflows", "retries & recovery", "long-running orchestration"], alternatives: ["inngest"] },
];

export const toolBySlug = (s) => TOOLS.find(t => t.slug === s) || null;
export const toolsInCategory = (c) => TOOLS.filter(t => t.category === c);
