// cover-coverage.test.js — INFORMATIONAL ONLY (never fails).
//
// Covers are deliberately NOT committed to git anymore. Committing every post's
// .png/.webp/.avif (and every mp3) had grown .git to 7.8 GB, which broke the cloud
// newsroom: its sandbox must clone the whole repo before writing, and a 7.8 GB
// clone was failing — stalling all content for ~48h (2026-07-16→18). We moved media
// out of git history; the server now serves covers from an untracked overlay
// (images-ai/, generated by scripts/ai-covers.js) and falls back to a branded
// placeholder for a not-yet-generated cover (server.js /images/:file). So a cover
// missing from the git tree is EXPECTED and never a broken image.
//
// This test therefore no longer gates anything — it just reports how many posts
// have a committed cover (should be ~0 now, plus legacy .jpg/.svg dispatch covers)
// so a regression that re-commits thousands of covers is visible in the log.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "..", "..");
const POSTS = path.join(REPO, "content", "posts");
const IMAGES = path.join(REPO, "images");

test("cover artifacts in git (informational — covers live in the server overlay, not git)", () => {
  const posts = fs.readdirSync(POSTS).filter((f) => f.endsWith(".md"));
  const have = new Set(fs.existsSync(IMAGES) ? fs.readdirSync(IMAGES) : []);
  let png = 0, opt = 0;
  for (const f of posts) {
    const slug = f.replace(/\.md$/, "");
    if (have.has(slug + ".png")) png++;
    if (have.has(slug + ".webp") || have.has(slug + ".avif")) opt++;
  }
  console.log(`  [cover-coverage] ${posts.length} posts · ${png} with a committed .png · ${opt} with webp/avif ` +
    `(covers are served from the server's images-ai/ overlay, not git — this is expected to be low).`);
  assert.ok(posts.length > 0, "expected at least one post");
});
